leaderboard_app/urls.py
from django.urls import path
from .views import leaderboard_view, leaderboard_update_api, add_lap_score
from django.contrib.auth.views import LoginView

app_name = "leaderboard_app"

urlpatterns = [
    path('', leaderboard_view, name='leaderboard'),
    path('api/leaderboard/', leaderboard_update_api, name='leaderboard_update_api'),
    path("add_lap_score/", add_lap_score, name="add_lap_score"),
    path("login/", LoginView.as_view(template_name="leaderboard_app/login.html"), name="login"),
]

raceapp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('leaderboard_app.urls'))
    
]

leaderboard_app/models.py
from django.db import models
from django.contrib.auth.models import User
from .fields import FloatListField

# Create your models here.

class Competitor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    laps = FloatListField(blank=True)
    current_best = models.FloatField(default = -1.0, blank=True)


    class Meta:
        ordering = ['current_best']

    def __str__(self):
        return f'{self.user.username + " - " + str(self.laps) + " - " + str(self.current_best)}'
    
    def update_current_best(self):
        lap_scores = self.laps
        if lap_scores is None or len(lap_scores) < 3:
            self.current_best = -1.0
            return
        current_best_consequetives = [-1,-1,-1]
        consequetive_queue_buffer = []        
        #cumulation = 0
        previous_lap_score = -1
        for lap_score in lap_scores:
            if lap_score <= 0:
                previous_lap_score = lap_score
                continue
            if previous_lap_score <= 0:
                #when the last lap is invalid, reset
                consequetive_queue_buffer = []
            cumulation = len(consequetive_queue_buffer)
            if cumulation < 2:
                consequetive_queue_buffer.append(lap_score)
            elif cumulation == 2:
                consequetive_queue_buffer.append(lap_score)
                if sum(consequetive_queue_buffer) < sum(current_best_consequetives) or sum(current_best_consequetives) < 0:
                    current_best_consequetives = consequetive_queue_buffer.copy()
            else:
                consequetive_queue_buffer.pop(0)
                consequetive_queue_buffer.append(lap_score)
                if sum(consequetive_queue_buffer) < sum(current_best_consequetives) or sum(current_best_consequetives) < 0:
                    current_best_consequetives = consequetive_queue_buffer.copy()
            previous_lap_score = lap_score
        
        if current_best_consequetives == [-1,-1,-1]:
            self.current_best = -1.0
        else:
            self.current_best = round(sum(current_best_consequetives),3)
        self.save()
        

leaderboard_app/forms.py
# forms.py
from django import forms
from .models import Competitor
from django.contrib.auth.models import User

class CompetitorAdminForm(forms.ModelForm):
    class Meta:
        model = Competitor
        fields = '__all__'
        widgets = {
            'laps': forms.TextInput (attrs = {'class': 'form-control form-control-sm'}),
        }

    def clean_laps(self):
        laps_str = self.cleaned_data['laps']
        if laps_str is "":
            try:
                laps = []
                return laps
            except ValueError:
                pass
        
        try:
            laps = [float(laps_str)]
            return laps
        except ValueError:
            pass
        try:
            laps = [float(x) for x in laps_str.split(',')]
            return laps
        except ValueError:
            pass
        try:
            laps = [float(x) for x in laps_str[1:-1].split(',')]
        except ValueError:
            raise forms.ValidationError("Invalid list of floats")
        return laps
    
class AddLapScoreForm(forms.Form):
  user = forms.ModelChoiceField(queryset=User.objects.all(), label="Competitor")
  lap_score = forms.FloatField(label="Lap Score")

leaderboard_app/views.py
from django.shortcuts import render,redirect
from .models import Competitor
from django.http import JsonResponse
from .forms import AddLapScoreForm
from .decorators import superuser_required
from django.db.models import Case, When, Value, FloatField
from django.db.models.functions import Coalesce

# Create your views here.
def leaderboard_view(request, *args, **kwargs):
    #all_competitors = Competitor.objects.all()
    #context = {'competitors': all_competitors}
    context = {}
    return render(request, "leaderboard_app/leaderboard.html",context)

def leaderboard_update_api(request, *args, **kwargs):
    all_competitors = Competitor.objects.order_by(
        Case(
            When(current_best__lte=0, then=Value(9999)),
            default='current_best',
            output_field=FloatField(),
        )
    )
    
    #all_competitors = Competitor.objects.all()
    for competitor in all_competitors:
        competitor.update_current_best()
    data = [{'name': competitor.user.username, 'laps': ' '.join([str(lap) if lap > 0 else "X" for lap in competitor.laps]), 'score': str(competitor.current_best)} for competitor in all_competitors]
    return JsonResponse(data, safe=False)


@superuser_required
def add_lap_score(request, *args, **kwargs):
  if request.method == "POST":
      form = AddLapScoreForm(request.POST)
      if form.is_valid():
          selected_user = form.cleaned_data["user"]
          lap_score = form.cleaned_data["lap_score"]

          competitor, created = Competitor.objects.get_or_create(user=selected_user)
          if competitor.laps is not None:
              competitor.laps.append(lap_score)
          else:
              competitor.laps = [lap_score]
          competitor.save()

          return redirect("leaderboard_app:add_lap_score")  # Replace "some_view" with the desired view to redirect to
  else:
      form = AddLapScoreForm()
  return render(request, "leaderboard_app/add_lap_score.html", {"form": form})

leaderboard_app/templates/leaderboard_app/add_lap_score.html
<!-- templates/add_lap_score.html -->
{% extends "base.html" %}
{% load static %}


{% block title %}
Add Lap Score
{% endblock %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/addlapscore.css' %}" />
{% endblock %}

{% block content %}
    <h1>Add Lap Score</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
{% endblock %}

leaderboard_app/templates/leaderboard_app/leaderboard.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Leaderboard
{% endblock %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/leaderboard.css' %}" />
{% endblock %}

{% block content %}
    <h1>Leaderboard</h1>
    
    <ul id="leaderboard">
      <!-- The list will be updated by JavaScript -->
      
    </ul>
    <script>
      const leaderboard = document.getElementById('leaderboard');

      function updateObjectList() {
          fetch('{% url "leaderboard_app:leaderboard_update_api" %}')
              .then((response) => response.json())
              .then((data) => {
                  leaderboard.innerHTML = '';
                  previous_score = -1.0;
                  competitor_index = 1;
                  competitor_rank = 1;
                  data.forEach((competitor) => {
                      // Create the 'li' element
                    const li = document.createElement('li');
                    li.classList.add('competitor_li');
                    //li.classList.add('animate__animated');
                    //li.classList.add('animate__pulse');
                    
                    if(competitor.score != previous_score){
                      competitor_rank = competitor_index
                    }
                    
                    const rankDiv = document.createElement('div');
                    rankDiv.classList.add('competitor_rank');
                    rankDiv.textContent = competitor_rank;
                    li.appendChild(rankDiv);

                    // Create the 'div' element for the competitor's name
                    const nameDiv = document.createElement('div');
                    nameDiv.classList.add('competitor_name');
                    nameDiv.textContent = competitor.name;
                    li.appendChild(nameDiv);

                    // Create the 'div' element for the competitor's score
                    const scoreDiv = document.createElement('div');
                    scoreDiv.classList.add('competitor_score');
                    parsed_score = parseFloat(competitor.score);
                    if(parsed_score <= 0 ){
                      scoreDiv.textContent = "--";
                      rankDiv.textContent = "--";
                    }else{
                      scoreDiv.textContent = competitor.score;
                    }
                    li.appendChild(scoreDiv);
                    
                    const lapsLabelDiv = document.createElement('div');
                    lapsLabelDiv.classList.add('competitor_laps_label');
                    lapsLabelDiv.textContent = "LAPS SCORE";
                    li.appendChild(lapsLabelDiv);

                    const lapsDiv = document.createElement('div');
                    lapsDiv.classList.add('competitor_laps');
                    lapsDiv.textContent = competitor.laps;
                    li.appendChild(lapsDiv);

                    // structure:
                    // <li class="competitor_li">
                    //   <div class="competitor_rank"></div>
                    //   <div class="competitor_name"></div>
                    //   <div class="competitor_score"></div>
                    //   <div class="competitor_laps_label">LAPS SCORE</div>
                    //   <div class="competitor_laps"></div>
                    // </li>

                    
                    leaderboard.appendChild(li);
                    previous_score = competitor.score;
                    competitor_index ++;
                  });
              });
      }

      // Call the function to update the list initially
      updateObjectList();

      // Periodically update the list every 5000 milliseconds (5 seconds)
      setInterval(updateObjectList, 1000);
    </script>
    <!--<script type="text/javascript" src="{% static "js/leaderboard_update.js" %}"></script>-->
{% endblock %}

leaderboard_app/templates/leaderboard_app/login.html
<!-- templates/login.html -->
{% extends "base.html" %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}" />
{% endblock %}

{% block title %}
Authentication Required
{% endblock %}

{% block content %}
    <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
{% endblock %}

templates/base.html
{% load static %}
<!-- templates/base.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Default Title{% endblock %}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;300;600;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    {% block head %}{% endblock %}
</head>
<body>
    <header>
        <!-- Add your site header content here -->
        {% block header %}{% endblock %}
    </header>

    <main>
        {% block content %}
        <!-- Default content can be placed here -->
        {% endblock %}
        <div class="lines">
            <div class="line"></div>
            <div class="line"></div>
            <div class="line"></div>
        </div>
    </main>

    <footer>
        <!-- Add your site footer content here -->
        {% block footer %}{% endblock %}
    </footer>
</body>
</html>